
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://kcjonesevans.github.io"
author_email: kcjonesevans@gmail.com


# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: /kcje-site/
baseurl: ""

# Google tracking id to track your visitors

google-tracking-id: "UA-74637360-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

#force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "K.C. Jones-Evans"
title: "{ K.C. Jones-Evans }"
description: "website of K.C. Jones-Evans"
keywords: "jones-evans, jones, evans, kc, k.c., gdi, programming"
favicon: "/img/black-cat-icon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: #"/img/black-cat-icon.ico"

background-img: "../img/coding1_bw.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Hello."
  - text: "Let's do some programming."

me-img: "/img/bw_profile.jpg"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/favicon-32x32.png"
icon-48p: "/img/web-app/favicon-32x32.png"
icon-72p: "/img/web-app/favicon-32x32.png"
icon-96p: "/img/web-app/favicon-96x96.png"
icon-144p: "/img/web-app/android-icon-144x144.png"
icon-192p: "/img/web-app/android-icon-192x192.png"


############
# Timeline #
############

events:
  - image: "/img/timeline/python.svg"
    date: "September 2010"
    description: "First Coding Job- Part-time Web Developer"
    url: ""
  - image: "/img/timeline/graduation.png"
    date: "June 2011"
    description: "Graduated WSU with BS in Computer Science"
    url: ""
  - image: "/img/timeline/marriage.png"
    date: "August 2012"
    description: "Married Kevin!"
    url: ""
  - image: "/img/timeline/wyoming.png"
    date: "August 2012"
    description: "Honeymoon in Jackson Hole, Wyoming"
    url: ""
  - image: "/img/timeline/jquery.svg"
    date: "September 2013"
    description: "Riverside Research Web Developer"
    url: ""
  - image: "/img/timeline/washingtondc.png"
    date: "December 2013"
    description: "Adventures In Washington D.C."
    url: ""
  - image: "/img/timeline/sanfran.png"
    date: "February 2014"
    description: "Exploring SanFran and the PCH"
    url: ""
  - image: "/img/timeline/seattle.png"
    date: "August 2014"
    description: "Seattle!"
    url: "https://goo.gl/photos/NdDDb83UMVdhHaKr8"
  - image: "/img/timeline/gdi-dayton-logo.png"
    date: "July 2015"
    description: "Girl Develop It Dayton Chapter Starts"
    url: "http://www.gdidayton.com"
  - image: "/img/timeline/tokyo.png"
    date: "October 2015"
    description: "Overseas to JAPAN!!!"
    url: "https://goo.gl/photos/9b6HZyVTZYPRY3LW7"
  - image: "/img/timeline/follybeach.png"
    date: "December 2015"
    description: "Southern Christmas in Charleston, SC"
    url: "https://goo.gl/photos/4nAY4RS35BUPqVgi7"
  - image: "/img/timeline/ruby.svg"
    date: "February 2016"
    description: "Teaching Ruby!"
    url: "http://www.meetup.com/Girl-Develop-It-Dayton/events/227940746/"
  - image: "/img/timeline/nodejs.svg"
    date: "March 2016"
    description: "New Job"
    url: ""


# First image of the Timeline

timeline-img: "img/black-cat-icon.ico"

##########
# Resume #
##########

experience:
    - name: Applied Information Sicence
      title: Software Engineer
      time: March 2016 - Present
      summary: Leading user experience for developers and desiging web applications with Angular, React/Redux and Node. 
    - name: Riverside Research
      title : Software Developer
      time: September 2013 - February 2016
      summary: Developed interactive dynamic web pages using Jquery, Perl, and an Oracle DB. Researched development issues, provided multiple solutions and implemented a solution in a team. Maintained metrics and statics of an Oracle DB.
    - name: Science Applications International Corporation
      title: Software Engineer
      time: September 2010 - September 2013
      summary: Support Small Business Innovation Research (or SBIR) program and other various programs needing software design and engineering. Leading and creating a  Python/Django application that uses entity , temportal , and geospacial extraction of web based media
    - name: Wright State University College of Engineering
      title: Programming Assistant and Teacher's Assistant
      time: April 2009 - October 2010
      summary: Teaching assistant for operating systems class covering file-system usage and design, process usage and control, virtual memory, multi user systems, access control. Provide assistance to Computer Science and Engineering students in Java & C/C++ introduction and intermediate level classes with debugging and solving issues with labs and projects.
    - name: Wright State University Collete of Math and Science
      title: Developmental Math 095 Proctor
      time: September 2008 - March 2010
      summary: Taught developmental algebra and pre-algebra concepts to college students.
    - name: The Reynolds and Reynolds Company
      title: Web Developer Intern
      time: Summer 2009
      summary: Internship as a Web Developer for Reynolds and Reynold's Marketing Department.

skills:
    - name: JavaScript
    - name: React and Redux
    - name: Angular
    - name: Node
    - name: Ruby and Ruby on Rails
    - name: Python and Django
    - name: Git
    - name: Jekyll
    - name: HTML/CSS
    - name: C/C++
    - name: C#
    - name: Visual Basic
    - name: Java
    - name: PostgreSQL and PostGIS
    - name: OpenGL
    - name: MatLab

publications:
    - title: Web-based Geospatial Information Extraction
      publisher: Proceedings of the IEEE 2012 NAECON
      link: http://ieeexplore.ieee.org/xpl/articleDetails.jsp?tp=&arnumber=6531027&queryText%3DBrian+Bacher+.PLS.+K.C.+Jones+.PLS.+Bart+Kahler
    - title: Language Translation of Web-based Content
      publisher: Proceedings of the IEEE 2012 NAECON
      link: http://ieeexplore.ieee.org/xpl/articleDetails.jsp?tp=&arnumber=6531026&queryText%3DBrian+Bacher+.PLS.+K.C.+Jones+.PLS.+Bart+Kahler

education:
    - school: Wright State Univerisy
      degree: Bachlors of Science in Computer Science
      time: June 2011

volunteer:
    - group: Girl Develop It Dayton Chapter (Dayton Women Code Together)
      title: Chapter Co-Lead
      time: August 2015 - January 2019
      summary: Girl Develop It is a nonprofit organization that provides affordable programs for adult women interested in learning web and software development in a judgment-free environment. The Dayton Chapter is now known as Dayton Women Code Together (https://www.meetup.com/Dayton-Code-Together/)

###########
# Courses #
###########
courses:
  - name: Introduction to Programming Concepts
    slides: "http://kcjonesevans.github.io/gdi-intro-programming-concepts/#/"
    repo: "https://github.com/kcjonesevans/gdi-intro-programming-concepts"
  - name: Introduction to Programming with Ruby
    slides: "http://kcjonesevans.github.io/gdidayton-intro-ruby/#/"
    repo: "https://github.com/kcjonesevans/gdidayton-intro-ruby"

###########
# Contact #
###########

email: "kcjonesevans@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "envelope"
    url: "mailto:kcjonesevans@gmail.com"
  - title: "twitter"
    url: "https://twitter.com/kcjonesevans"
  - title: "github"
    url: "https://github.com/kcjonesevans"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/kcjonesevans"
  - title: "instagram"
    url: "https://www.instagram.com/kcjonesevans/"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Resume: 'resume'
  Contact: 'contact'



# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
